### PR TITLE
Upgrade to latest upstream 4.9.8

### LINKED ISSUE #7: phpMyAdmin 4.9.8 released
I see this version [released](https://www.phpmyadmin.net/files/4.9.8/). It fixes [PMASA-2022-1](https://www.phpmyadmin.net/security/PMASA-2022-1/), so I wanted to ask if there are any plans to add it to the repo.

### LINKED ISSUE #8: Remove php-recode from dependencies
phpMyAdmin49 (4.9.7) [requires](https://github.com/iusrepo/phpMyAdmin49/blob/c74d84d4e01ec8af2c12f08865b55a20b091f28b/phpMyAdmin49.spec#L82) `php-recode` which can't be provided in PHP 7.4 since "_[This extension has been moved to the » PECL repository and is no longer bundled with PHP as of PHP 7.4.0](https://www.php.net/manual/en/recode.installation.php)_", however, it has [no releases in PECL](https://pecl.php.net/package/recode). Simply, it was abandoned since PHP 7.4, proof [here](https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1735607.html).

Problem is that IUS, doesn't removed it from [dependencies](https://github.com/iusrepo/phpMyAdmin49/blob/c74d84d4e01ec8af2c12f08865b55a20b091f28b/phpMyAdmin49.spec#L82) too, which leads to conflict so PMA wants to downgrade PHP to 7.3 (which is EOL) which only one provides this dependency. 

```
$ sudo yum install phpMyAdmin49
...
Resolving Dependencies
--> Running transaction check
---> Package phpMyAdmin49.noarch 0:4.9.7-1.el7.ius will be installed
--> Processing Dependency: php-recode for package: phpMyAdmin49-4.9.7-1.el7.ius.noarch
--> Processing Dependency: php-mysqli for package: phpMyAdmin49-4.9.7-1.el7.ius.noarch
--> Running transaction check
---> Package php73-recode.x86_64 0:7.3.33-1.el7.ius will be installed
--> Processing Dependency: php-common(x86-64) = 7.3.33-1.el7.ius for package: php73-recode-7.3.33-1.el7.ius.x86_64
--> Processing Dependency: librecode.so.0()(64bit) for package: php73-recode-7.3.33-1.el7.ius.x86_64
---> Package php74-mysqlnd.x86_64 0:7.4.27-1.el7.ius will be installed
--> Processing Dependency: php-pdo(x86-64) = 7.4.27-1.el7.ius for package: php74-mysqlnd-7.4.27-1.el7.ius.x86_64
--> Running transaction check
---> Package php73-common.x86_64 0:7.3.33-1.el7.ius will be installed
---> Package php74-pdo.x86_64 0:7.4.27-1.el7.ius will be installed
---> Package recode.x86_64 0:3.6-38.el7 will be installed
--> Processing Conflict: php74-common-7.4.27-1.el7.ius.x86_64 conflicts php-common < 7.4.27-1.el7.ius
--> Processing Conflict: php74-common-7.4.27-1.el7.ius.x86_64 conflicts php73-common
...

$ sudo yum deplist phpMyAdmin49
...
package: phpMyAdmin49.noarch 4.9.7-1.el7.ius
  ...
  dependency: php-recode
   provider: php73-recode.x86_64 7.3.33-1.el7.ius
   provider: php-recode.x86_64 5.4.16-48.el7
  ...
```

And BTW officially "[_...compatible with PHP 5.5 to 7.4 and MySQL/MariaDB 5.5..._](https://www.phpmyadmin.net/files/4.9.7/#:~:text=older%20version%20compatible%20with%20php%205.5%20to%207.4%20and%20mysql%2Fmariadb%205.5%20and%20newer.)", it stated that 4.9.7 should work with PHP 7.4.

Can you please remove `php-recode` from dependencies and rebuild the rpm?

### PR DESCRIPTION
**Pull request by jbartak**
Closes https://github.com/iusrepo/phpMyAdmin49/issues/8.
Closes https://github.com/iusrepo/phpMyAdmin49/issues/7.

### CODE REVIEW

**Comment by jbartak** [comment]
@carlwgeorge can you please review this?

**Review by liamsorsby — APPROVED** [review]

**Comment by lubo** [comment]
@carlwgeorge Ping.

**Comment by carlwgeorge** [comment]
phpMyAdmin49-4.9.8-1.el7.ius has been built and pushed to the testing repo.

**Comment by petecassetta** [comment]
I've tested phpMyAdmin49-4.9.8-1.el7.ius and it looks good to me.

**Comment by carlwgeorge** [comment]
Thanks for testing Pete, I've promoted that build to the main repo.

**Pull request merged**
